import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, BookOpen, Check, CheckCircle2, ChevronDown, Circle, Code2, GitBranch, Github, LayoutDashboard, RefreshCw, Route, Sprout, Terminal, Waypoints} from 'lucide-react';
import './style.css';
import GitHubAccount from './GitHubAccount.jsx';
import logo from './assets/episteme-light.png';

const labels={completed:'Checks met',in_progress:'In progress',not_started:'Not started'};
const date=(value)=>new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function App(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[page,setPage]=useState('overview'),[notice,setNotice]=useState('');
 async function load(){const res=await fetch('/api/progress');if(!res.ok)throw new Error('Progress could not be loaded. Check that the backend is running.');setData(await res.json());}
 useEffect(()=>{load().catch(e=>setError(e.message));const timer=setInterval(()=>load().catch(()=>{}),30000);return()=>clearInterval(timer);},[]);
 async function sync(){if(repository.trim()!==data?.repository||root.trim()!==data?.root){return connect({preventDefault(){}});}setBusy(true);setError('');setNotice('');try{const res=await fetch('/api/sync',{method:'POST',headers:{'X-Episteme-Client':'dashboard'}});const body=await res.json();if(!res.ok)throw new Error(body.detail||'Sync failed. Please try again.');await load();setNotice('Latest GitHub evidence saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const [repository,setRepository]=useState(''),[root,setRoot]=useState('projects'),[connecting,setConnecting]=useState(false),[connectionError,setConnectionError]=useState('');
 useEffect(()=>{if(data){setRepository(data.repository);setRoot(data.root??'projects');}},[data?.repository,data?.root]);
 async function connect(e){e.preventDefault();setConnecting(true);setConnectionError('');setNotice('');try{const res=await fetch('/api/connection',{method:'PUT',headers:{'Content-Type':'application/json','X-Episteme-Client':'dashboard'},body:JSON.stringify({repository,root})});const body=await res.json();if(!res.ok)throw new Error(typeof body.detail==='string'?body.detail:'Check the repository and project folder.');await load();setRepository(body.repository);setRoot(body.root);setNotice('Repository connected and progress synced.');}catch(e){setConnectionError(e.message);}finally{setConnecting(false);}}
 const repoName=data?.repository?.split('/')[1]||'Repository';
 const repoUrl=data?.repository?'https://github.com/'+data.repository:'#main';
 const selectionChanged=!!data&&(repository.trim()!==data.repository||root.trim()!==data.root);
 const current=data?.projects.find(p=>p.status!=='completed');
 return <div className="app"><a className="skip" href="#main">Skip to content</a><aside className="sidebar"><a className="brand" href="#" onClick={()=>setPage('overview')}><img className="brand-lockup" src={logo} alt="Episteme — dashboard" width="216" height="72"/></a><div className="workspace-label">PERSONAL WORKSPACE</div><nav aria-label="Main navigation">{[['overview','Dashboard',LayoutDashboard],['roadmap','My roadmap',Route],['activity','Sync history',Waypoints]].map(([id,name,Icon])=><button key={id} className={page===id?'nav active':'nav'} aria-current={page===id?'page':undefined} onClick={()=>setPage(id)}><Icon size={19}/>{name}{page===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-note"><div className="tiny-icon"><BookOpen size={19}/></div><strong>Little by little.<br/>Build something real.</strong><p>Your progress is a record of the work you put in.</p><a href={repoUrl} target="_blank" rel="noreferrer">Open {repoName} <ArrowUpRight size={15}/></a></div><div className="profile"><span className="avatar">ET</span><div><strong>Eleazar Torres</strong><small>Personal learning journey</small></div></div></aside>
 <div className="main-shell"><header className="topbar"><div>Workspace <span>/</span> <b>{page==='overview'?'Dashboard':page==='roadmap'?'My roadmap':'Sync history'}</b></div><a href={repoUrl} target="_blank" rel="noreferrer"><Github size={16}/> {repoName} <ArrowUpRight size={14}/></a></header><main id="main"><section className="page-heading"><div><span className="eyebrow">LEARNING, ONE COMMIT AT A TIME</span><h1>{page==='overview'?'Small steps. Real progress.':page==='roadmap'?'Your path forward.':'Every sync, accounted for.'}</h1><p>{page==='overview'?'A clear view of what you’re building, and what comes next.':page==='roadmap'?'Three starter milestones. Build, explain, commit, then sync.':'Saved snapshots of your learning repository.'}</p></div><button className="sync-button" disabled={busy||connecting} onClick={sync}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Syncing GitHub…':connecting?'Connecting…':selectionChanged?'Sync selected repository':'Sync GitHub'}</button></section>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>Retry loading</button></div>}<div role="status" className={notice?'notice':'sr-only'}>{notice}</div>
 {!data?<div className="loading" aria-busy="true">Loading your learning workspace…</div>:<>
 {page==='overview'&&<section className="connection-panel"><div><span className="eyebrow">YOUR SOURCE OF PROGRESS</span><h2>Repository connection</h2><p>Choose any repository. Your project folders tell Episteme what to check.</p><small>Currently synced repository</small><a href={repoUrl} target="_blank" rel="noreferrer"><Github size={16}/> {data.repository} <ArrowUpRight size={14}/></a></div><form onSubmit={connect}><GitHubAccount disabled={busy||connecting} onSelect={name=>{setRepository(name);setConnectionError('');}}/><div className="connection-fields"><label>GitHub repository<input required value={repository} onChange={e=>setRepository(e.target.value)} placeholder="owner/repository or GitHub URL" aria-describedby="connection-help" autoComplete="off"/></label><label>Projects parent folder<input value={root} onChange={e=>setRoot(e.target.value)} placeholder="Blank for repository root" aria-describedby="connection-help" autoComplete="off"/></label></div><p className="selection-notice" role="status">{selectionChanged?'New selection is not connected yet. Sync it to update all repository links and progress.':'All repository links use the saved connection shown here.'}</p><p id="connection-help">Looks for 01-temperature, 02-expenses and 03-file-reader inside this folder. Each connection keeps its own progress.</p>{connectionError&&<p className="connection-error" role="alert">{connectionError}</p>}<button className="sync-button" disabled={connecting||busy} type="submit"><GitBranch size={16}/>{connecting?'Connecting…':'Connect & sync'}</button></form></section>}
 {page==='overview'&&<><section className="hero-grid"><div className="progress-card"><div className="card-top"><span className="pill"><span/> YOUR LEARNING JOURNEY</span><span className="muted">Python foundations</span></div><div className="progress-layout"><div><h2>Keep your curiosity<br/>moving forward.</h2><p>Every project is another piece of the picture.</p></div><div className="percent">{data.percent}<span>%</span><small>of milestone checks met</small></div></div><progress max="100" value={data.percent} aria-label="Overall milestone progress"/><div className="progress-meta"><span><strong>{data.completed}</strong> of {data.total} milestones checked</span><span>{data.total-data.completed} to explore <ArrowRight size={14}/></span></div><div className="hero-footer"><span><GitBranch size={15}/> {repoName}</span><span>{data.last_sync?'Last synced '+date(data.last_sync.created_at):'Ready for your first sync'}</span></div></div><div className="next-card"><span className="eyebrow">UP NEXT</span><div className="next-icon"><Terminal size={25}/></div><small>{current?.id||'WELL DONE'} · {current?.category||'Starter path'}</small><h2>{current?.title||'A foundation to build on'}</h2><p>{current?.description||'All starter source checks are met. Review your solutions and add a new milestone.'}</p><button onClick={()=>{setPage('roadmap');setFilter('all');}}>Explore the milestone <ArrowRight size={17}/></button></div></section><section className="stats"><div><span className="stat-icon"><CheckCircle2 size={20}/></span><div><small>Milestones checked</small><strong>{String(data.completed).padStart(2,'0')} <span>/ {String(data.total).padStart(2,'0')}</span></strong></div></div><div><span className="stat-icon amber"><Code2 size={20}/></span><div><small>In progress</small><strong>{String(data.projects.filter(p=>p.status==='in_progress').length).padStart(2,'0')}</strong></div></div><div><span className="stat-icon"><GitBranch size={20}/></span><div><small>Repository</small><strong className="repo-stat">{repoName} <span>{data.last_sync?'Synced':'Awaiting sync'}</span></strong></div></div></section></>}
 {page!=='activity'&&<section className="roadmap"><div className="section-title"><div><h2>Your roadmap <span>{data.total} milestones</span></h2><p>A little structure for your next big idea.</p></div><label className="filter">Show <select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter milestones"><option value="all">All milestones</option><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="completed">Checks met</option></select></label></div><div className="project-list">{data.projects.filter(p=>filter==='all'||p.status===filter).map((p,index)=><details className="project" key={p.id}><summary><span className={'step '+p.status}>{p.status==='completed'?<Check size={18}/>:p.id.slice(-2)}</span><div className="project-name"><small>{p.category}</small><h3>{p.title}</h3></div><span className={'status '+p.status}><span/>{labels[p.status]}</span><ChevronDown size={17} className="chevron"/></summary><div className="project-body"><p>{p.description}</p><code>{p.path}/main.py</code><ul>{p.checks.map(c=><li key={c.label}><span className="sr-only">{c.passed?'Passed: ':'Missing: '}</span>{c.passed?<CheckCircle2 size={17}/>:<Circle size={17}/>} {c.label}</li>)}</ul><a href={repoUrl} target="_blank" rel="noreferrer">Build in {repoName} <ArrowUpRight size={15}/></a></div></details>)}{!data.projects.some(p=>filter==='all'||p.status===filter)&&<p className="empty">No milestones here yet. Your next sync will update this view.</p>}</div><p className="method"><BookOpen size={16}/><span>Progress measures source checks, not code correctness or mastery. Open a milestone to see exactly what is checked.</span></p></section>}
 {page==='activity'&&<section className="roadmap"><h2>Repository snapshots</h2><p className="muted">Each successful sync is stored in your local SQL database.</p>{data.activity.length?data.activity.map(a=><div className="activity" key={a.id}><GitBranch size={18}/><div><strong>{a.source==='webhook'?'GitHub push received':'Manual GitHub sync'}</strong><p>{date(a.created_at)}</p></div><a href={repoUrl+'/commit/'+a.sha} target="_blank" rel="noreferrer">{a.sha.slice(0,7)} <ArrowUpRight size={14}/></a></div>):<div className="empty">No snapshots yet. Select Sync GitHub to read your first commit.</div>}</section>}
 <footer><span><span className="connection-dot"/>{data.last_sync?'GitHub evidence saved':'GitHub repository ready'} <span className="footer-divider">·</span> SQLite storage</span><span>{data.webhook_configured?'Webhook receiver configured · delivery requires hosting':'Manual sync active · automatic webhooks not connected'}</span></footer></>}
 </main></div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
